// Generated by CoffeeScript 1.10.0
exports.check = function() {
  var APICN_URL, YOUR_HOOK_URL, cheerio, request, url;

  request = require('request');

  url = require('url');

  cheerio = require('cheerio');

  APICN_URL = "http://aqicn.org/city/beijing/cn";

  YOUR_HOOK_URL = "https://hook.bearychat.com/=bw52Y/incoming/a071d01e86466eaa15fd5462e6c2db4a";

  request(APICN_URL, function(error, response, body) {
    var aqi, date, text, update;
    if (!error && response.statusCode === 200) {
      global.$ = cheerio.load(response.body);
      date = new Date();
      aqi = $('.api .aqivalue').text();
      update = $(".aqiwidget .aqivalue").last().next().next().text();
      text = "北京当前 AQI 指数是 **" + aqi + "** " + update + " | 数据来源： " + APICN_URL;
      console.log(text);
      return request({
        url: YOUR_HOOK_URL,
        method: "POST",
        headers: {
          'Content-Type': 'application/json; charset=UTF-8'
        },
        body: JSON.stringify({
          payload: JSON.stringify({
            text: text
          })
        })
      }, function(error, response, body) {
        return console.log(body);
      });
    }
  });

};
